# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Winged Five Games
email: info@wingedfivegames.com
logo: '/assets/decor/winged-five-games-wordmark-color-alt-cropped.png'
google_analytics: 'UA-102257607-1'
contact: Contact us
media: '@wingedfivegames'
mission: Play with big ideas!
description: Play with big ideas!
footer_bug: '/assets/decor/winged-five-logo-color-alt.png'
call_to_action: We make custom games.
copyright: Copyright © 2017-2023 Winged Five Games, LLC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wingedfivegames.com" # the base hostname & protocol for your site, e.g. http://example.com
site.title_image: '/assets/decor/winged-five-logo-color-alt.png'
facebook_username: WingedFive
twitter_username: wingedfivegames
instagram_username: wingedfivegames
github_username:  wingedfivegames
youtube_username:  UCXj77TqRctZHr6twAIUttlQ
linkedin_username_disabled:  wingedfivegames

# Build settings
markdown: kramdown
# theme: minima
plugins_dir:
  - jekyll-feed

# custom collections
collections:
  features:
    output: false
  games:
    output: true
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /posts/:name

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
